const S=[
[78,"An-Naba","النبأ",40],[79,"An-Nazi'at","النازعات",46],[80,"'Abasa","عبس",42],[81,"At-Takwir","التكوير",29],[82,"Al-Infitar","الإنفطار",19],[83,"Al-Mutaffifin","المطففين",36],[84,"Al-Inshiqaq","الإنشقاق",25],[85,"Al-Buruj","البروج",22],[86,"At-Tariq","الطارق",17],[87,"Al-A'la","الأعلى",19],[88,"Al-Ghashiyah","الغاشية",26],[89,"Al-Fajr","الفجر",30],[90,"Al-Balad","البلد",20],[91,"Ash-Shams","الشمس",15],[92,"Al-Layl","الليل",21],[93,"Ad-Duha","الضحى",11],[94,"Ash-Sharh","الشرح",8],[95,"At-Tin","التين",8],[96,"Al-'Alaq","العلق",19],[97,"Al-Qadr","القدر",5],[98,"Al-Bayyinah","البينة",8],[99,"Az-Zalzalah","الزلزلة",8],[100,"Al-'Adiyat","العاديات",11],[101,"Al-Qari'ah","القارعة",11],[102,"At-Takathur","التكاثر",8],[103,"Al-'Asr","العصر",3],[104,"Al-Humazah","الهمزة",9],[105,"Al-Fil","الفيل",5],[106,"Quraysh","قريش",4],[107,"Al-Ma'un","الماعون",7],[108,"Al-Kawthar","الكوثر",3],[109,"Al-Kafirun","الكافرون",6],[110,"An-Nasr","النصر",3],[111,"Al-Masad","المسد",5],[112,"Al-Ikhlas","الإخلاص",4],[113,"Al-Falaq","الفلق",5],[114,"An-Nas","الناس",6]
].map(x=>({no:x[0],name:x[1],ar:x[2],ayat:x[3]}));
const R=[['Mishary Rashid Alafasy','Alafasy_128kbps'],['Maher Al Muaiqly','MaherAlMuaiqly128kbps'],['Mahmoud Khalil Al-Husary','Husary_128kbps'],['Muhammad Siddiq Al-Minshawi','Minshawy_Murattal_128kbps'],['Abdurrahman As-Sudais','Abdurrahmaan_As-Sudais_192kbps']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],K='hifdh-v3',QK='hifdh-quran-v1';
const iso=d=>new Date(d).toISOString().slice(0,10),today=()=>iso(new Date()),add=(d,n)=>{let x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return iso(x)},diff=(a,b)=>Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000);
function fresh(){return{plan:{days:90,start:today(),minutes:30},reciter:0,speed:1,records:Object.fromEntries(S.map(s=>[s.no,{status:'new',confidence:1,reps:0,ease:2.5,interval:0,next:today(),notes:''}])),activity:{},reviews:0,github:{token:'',gist:''}}}
let st=(()=>{try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(K)||'{}'))}catch{return fresh()}})(),quran=JSON.parse(localStorage.getItem(QK)||'null'),filter='all',calDate=new Date(),installPrompt,recorder,chunks=[];
const rec=n=>st.records[n],save=()=>{localStorage.setItem(K,JSON.stringify(st));render()},toast=m=>{let t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)},label=x=>({new:'Not started',learning:'Learning',memorised:'Memorised',retained:'Retained'})[x],pad=n=>String(n).padStart(3,'0');
function due(){return S.filter(s=>rec(s.no).status!=='new'&&rec(s.no).next<=today())}function streak(){let n=0,d=new Date();while(st.activity[iso(d)]?.sessions){n++;d.setDate(d.getDate()-1)}return n}function dayNo(){return Math.max(1,diff(st.plan.start,today())+1)}
function targets(){let rem=S.slice().reverse().filter(s=>!['memorised','retained'].includes(rec(s.no).status)),days=Math.max(1,st.plan.days-dayNo()+1),goal=Math.ceil(rem.reduce((a,s)=>a+s.ayat,0)/days),n=0,out=[];for(let s of rem){out.push(s);n+=s.ayat;if(n>=goal)break}return out}
function renderToday(){let total=S.reduce((a,s)=>a+s.ayat,0),done=S.reduce((a,s)=>a+(['memorised','retained'].includes(rec(s.no).status)?s.ayat:rec(s.no).status==='learning'?Math.ceil(s.ayat*.35):0),0),p=Math.round(done/total*100);$('#pct').textContent=p+'%';$('#ring').style.setProperty('--p',p+'%');$('#streak').textContent=streak()+' days';$('#due').textContent=due().length;$('#memorised').textContent=S.filter(s=>['memorised','retained'].includes(rec(s.no).status)).length+' / 37';$('#reviews').textContent=st.reviews;$('#planSummary').textContent=`Day ${Math.min(dayNo(),st.plan.days)} of ${st.plan.days} • ${st.plan.minutes} minutes daily`;
$('#targets').innerHTML=targets().map(s=>`<div class="target"><div><b>${s.name}</b><div class="arabic">${s.ar}</div><span class="meta">${s.ayat} Ayat</span></div><button onclick="openSurah(${s.no})">Open</button></div>`).join('')||'<p>All Surahs memorised. Focus on retention.</p>';
$('#queue').innerHTML=due().map(s=>`<div class="review"><div><b>${s.name}</b><div class="arabic">${s.ar}</div><span class="meta">Interval ${rec(s.no).interval} days</span></div><div><button class="quality again" onclick="review(${s.no},1)">Again</button> <button class="quality hard" onclick="review(${s.no},3)">Hard</button> <button class="quality easy" onclick="review(${s.no},5)">Easy</button></div></div>`).join('')||'<p class="hint">Nothing is due today.</p>'}
function renderSurahs(){let query=$('#search').value.trim().toLowerCase();if(query&&quran){$('#surahGrid').innerHTML='';$('#ayahResults').innerHTML=quran.filter(a=>a.ar.includes(query)||a.en.toLowerCase().includes(query)||`${a.s}:${a.a}`.includes(query)||S.find(x=>x.no===a.s).name.toLowerCase().includes(query)).slice(0,80).map(a=>`<div class="ayah"><b>${S.find(x=>x.no===a.s).name} ${a.s}:${a.a}</b><div class="arabic">${a.ar}</div><div class="translation">${a.en}</div><button onclick="playAyah(${a.s},${a.a})">▶ Play</button></div>`).join('')||'<p>No results.</p>';return}$('#ayahResults').innerHTML='';$('#surahGrid').innerHTML=S.filter(s=>(filter==='all'||rec(s.no).status===filter)&&(!query||s.name.toLowerCase().includes(query)||s.ar.includes(query))).map(s=>`<div class="surah" onclick="openSurah(${s.no})"><div><span class="status">${label(rec(s.no).status)}</span><h3>${s.no}. ${s.name}</h3><div class="meta">${s.ayat} Ayat • next ${rec(s.no).next}</div></div><div class="arabic">${s.ar}</div></div>`).join('')}
async function loadQ(){if(quran)return quran;toast('Loading Qur’an text…');let [ar,en]=await Promise.all([fetch('https://api.alquran.cloud/v1/juz/30/quran-uthmani').then(r=>r.json()),fetch('https://api.alquran.cloud/v1/juz/30/en.sahih').then(r=>r.json())]);quran=ar.data.ayahs.map((x,i)=>({s:x.surah.number,a:x.numberInSurah,ar:x.text,en:en.data.ayahs[i]?.text||''}));localStorage.setItem(QK,JSON.stringify(quran));toast('Text saved for offline use');return quran}
async function openSurah(no){try{await loadQ()}catch{return toast('Connect once to download Qur’an text.')}let s=S.find(x=>x.no===no),r=rec(no),a=quran.filter(x=>x.s===no);$('#dialogBody').innerHTML=`<small>SURAH ${no}</small><h2>${s.name}</h2><div class="arabic">${s.ar}</div><p>${s.ayat} Ayat • ${label(r.status)}</p><div class="dialog-controls"><button onclick="setStatus(${no},'learning')">Start learning</button><button onclick="setStatus(${no},'memorised')">Mark memorised</button><button onclick="playSurah(${no})">▶ Play Surah</button><button id="recordBtn" onclick="recordAudio(${no})">● Record</button></div><label>Tajweed and hesitation notes<textarea id="notes" rows="3">${r.notes||''}</textarea></label><button onclick="saveNotes(${no})">Save notes</button><div class="ayahList">${a.map(x=>`<div class="ayahRow"><b>${x.s}:${x.a}</b> <button onclick="playAyah(${x.s},${x.a})">▶</button><div class="arabic">${x.ar}</div><div class="translation">${x.en}</div></div>`).join('')}</div>`;$('#dialog').showModal()}
function setStatus(no,x){let r=rec(no);r.status=x;if(x==='memorised'){r.interval=1;r.next=add(today(),1)}save();openSurah(no)}function saveNotes(no){rec(no).notes=$('#notes').value;save();toast('Notes saved')}
function review(no,q){let r=rec(no);r.reps++;r.confidence=q;if(q<3){r.interval=1;r.reps=0;r.ease=Math.max(1.3,r.ease-.2)}else{r.interval=r.reps===1?1:r.reps===2?3:Math.max(1,Math.round(r.interval*r.ease));r.ease=Math.max(1.3,r.ease+(q===5?.1:-.05))}r.next=add(today(),r.interval);if(r.status==='memorised'&&r.reps>=5&&r.interval>=21)r.status='retained';st.reviews++;log('reviews');save();toast('Next review in '+r.interval+' day(s)')}
function log(k){st.activity[today()]||={sessions:0,reviews:0};st.activity[today()][k]=(st.activity[today()][k]||0)+1}$('#complete').onclick=()=>{log('sessions');targets().forEach(s=>{if(rec(s.no).status==='new')rec(s.no).status='learning'});save();toast('Session completed. May Allah place barakah in it.')};
function playAyah(s,a){let p=$('#audio'),folder=R[st.reciter]?.[1]||R[0][1];p.src=`https://everyayah.com/data/${folder}/${pad(s)}${pad(a)}.mp3`;p.playbackRate=st.speed;p.play().catch(()=>toast('Audio unavailable'))}async function playSurah(no){await loadQ();let a=quran.filter(x=>x.s===no),i=0,p=$('#audio');function next(){if(i>=a.length)return;p.onended=()=>{i++;next()};playAyah(no,a[i].a)}next()}
async function recordAudio(no){if(recorder?.state==='recording'){recorder.stop();return}try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));a.download=`surah-${no}-recitation.webm`;a.click();stream.getTracks().forEach(t=>t.stop());toast('Recording saved')};recorder.start();$('#recordBtn').textContent='■ Stop and save'}catch{toast('Microphone permission not granted')}}
function renderCal(){let y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());$('#month').textContent=calDate.toLocaleDateString(undefined,{month:'long',year:'numeric'});let out='';for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let k=iso(d),a=st.activity[k],c=['day'];if(d.getMonth()!==m)c.push('other');if(k===today())c.push('today');if(a?.sessions||a?.reviews)c.push('done');out+=`<div class="${c.join(' ')}"><b>${d.getDate()}</b><span>${a?`${a.sessions||0} session • ${a.reviews||0} reviews`:''}</span></div>`}$('#cal').innerHTML=out}
function prep(c){let d=devicePixelRatio||1,w=c.clientWidth||450,h=260;c.width=w*d;c.height=h*d;let x=c.getContext('2d');x.scale(d,d);return[x,w,h]}function charts(){let vals=['new','learning','memorised','retained'].map(k=>S.filter(s=>rec(s.no).status===k).length),[x,w,h]=prep($('#statusChart')),cols=['#d7d8d2','#c49a4a','#2e7b67','#173d34'],ang=-Math.PI/2;vals.forEach((v,i)=>{let n=ang+v/37*Math.PI*2;x.beginPath();x.arc(w*.3,125,76,ang,n);x.lineWidth=28;x.strokeStyle=cols[i];x.stroke();ang=n});['Not started','Learning','Memorised','Retained'].forEach((l,i)=>{x.fillStyle=cols[i];x.fillRect(w*.57,48+i*38,12,12);x.fillStyle='#334';x.fillText(`${l}: ${vals[i]}`,w*.57+20,59+i*38)});let b=[];for(let i=13;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let a=st.activity[iso(d)]||{};b.push((a.sessions||0)+(a.reviews||0))}let [z,W,H]=prep($('#activityChart')),max=Math.max(1,...b),bw=(W-35)/14-5;z.fillStyle='#2e7b67';b.forEach((v,i)=>z.fillRect(22+i*(bw+5),H-25-(H-50)*v/max,bw,(H-50)*v/max));$('#retention').innerHTML=S.slice().sort((a,b)=>rec(a.no).confidence-rec(b.no).confidence).slice(0,10).map(s=>`<div class="retrow"><span>${s.name}</span><div class="bar"><i style="width:${rec(s.no).confidence*20}%"></i></div><b>${rec(s.no).confidence}/5</b></div>`).join('')}
function settings(){$('#days').value=st.plan.days;$('#start').value=st.plan.start;$('#minutes').value=st.plan.minutes;$('#reciter').innerHTML=R.map((r,i)=>`<option value="${i}" ${i===+st.reciter?'selected':''}>${r[0]}</option>`).join('');$('#speed').value=st.speed;$('#token').value=st.github.token||'';$('#gist').value=st.github.gist||'';$('#storage').textContent=quran?'Qur’an text is available offline.':'Qur’an text is not cached yet.'}
function render(){renderToday();renderSurahs();renderCal();settings()}$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='progress')setTimeout(charts,20)});$$('#filters button').forEach(b=>b.onclick=()=>{$$('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderSurahs()});$('#search').oninput=async()=>{if($('#search').value.length>2&&!quran)try{await loadQ()}catch{}renderSurahs()};$('#prev').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCal()};$('#next').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCal()};
$('#savePlan').onclick=()=>{st.plan={days:+$('#days').value,start:$('#start').value||today(),minutes:+$('#minutes').value};save();toast('Plan saved')};$('#reciter').onchange=e=>{st.reciter=+e.target.value;save()};$('#speed').onchange=e=>{st.speed=+e.target.value;save()};$('#cacheText').onclick=()=>loadQ().then(render).catch(()=>toast('Download failed'));$('#export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(st,null,2)],{type:'application/json'}));a.download='hifdh-backup.json';a.click()};$('#import').onchange=e=>{let r=new FileReader();r.onload=()=>{try{st=JSON.parse(r.result);save();toast('Backup restored')}catch{toast('Invalid backup')}};r.readAsText(e.target.files[0])};$('#reset').onclick=()=>{if(confirm('Delete all progress?')){st=fresh();save()}};
async function gist(method,id,body){let token=$('#token').value.trim();if(!token)throw Error('Add a GitHub token first');let r=await fetch('https://api.github.com/gists'+(id?'/'+id:''),{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error((await r.json()).message);return r.json()}$('#push').onclick=async()=>{try{let id=$('#gist').value.trim(),o=await gist(id?'PATCH':'POST',id,{description:'Hifdh Companion backup',public:false,files:{'hifdh-backup.json':{content:JSON.stringify(st)}}});st.github={token:$('#token').value.trim(),gist:o.id};save();toast('Synced to private Gist')}catch(e){toast(e.message)}};$('#pull').onclick=async()=>{try{let id=$('#gist').value.trim(),o=await gist('GET',id),raw=o.files['hifdh-backup.json'].content,token=$('#token').value.trim();st=JSON.parse(raw);st.github={token,gist:id};save();toast('Restored from GitHub')}catch(e){toast(e.message)}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});$('#install').onclick=async()=>{installPrompt.prompt();await installPrompt.userChoice;$('#install').hidden=true};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));render();
